### ISSUE TITLE
"Please select a page in the pagetree"

### ISSUE THREAD

**Issue by superscotty19** [kaystrobach/TYPO3.piwikintegration#49]
Hi again,

I love this extension so much that I want to make it the default start page for users when they login to TYPO3 backend. However, even though I've set the TSConfig to have:

setup.defaults.startModule = web_PiwikintegrationMod2
setup.override.startModule = web_PiwikintegrationMod2

... all I get upon login is:

"Please select a page in the pagetree"

Is there a way to give Piwikintegration the ability to know the user's DB mount/site root and automatically redirect to it?

Thanks!
-Scott.

**Comment by kaystrobach** [comment]
i need to think about it ... 

basicly there are 2 options:

* either store a default on in the user or via pagets
* select a page in tree on load

imho the last one is the way to go, but i do not know a way to do that in TYPO3

**Comment by pgampe** [comment]
AFAIK this is a missing feature in TYPO3. The same problem arises with page and list module (actually any web module) and the file list.

**Comment by DavidBruchmann** [comment]
If like that the values stored in the uc field are taken. So the first page
the message is shown because the page opens the page uid=0, later it opens
then the last chosen page.
Means it's a user setting and might be influenced perhaps by userTS or
pageTS?
Assumed that was is not possible there still is the general option using
hooks, but I don't know which one or even if a hook for this purpose exists.

**Comment by superscotty19** [comment]
An idea ...
If I right click -> "view frame source" on the right/piwik frame in TYPO3, I get a link like this:
http://mysite.ca/typo3conf/piwik/piwik/index.php?module=CoreHome&action=index&period=week&date=yesterday&idSite=1#/module=Dashboard&action=embeddedIndex&period=week&date=yesterday&idSite=1&idDashboard=1

If I replace idSite=1 with my root page PID (ex. idSite=929), then it works. Again, this is a manual intervention, but my idea is, what if the URL could be changed by piwik? That is, before constructing the URL to display in the frame, it performed a DB lookup to get the root page and then pass that to idSite?

**Comment by kaystrobach** [comment]
as @pgampe said, this is a TYPO3 problem.
Maybe you should open a Ticket in the TYPO3 tracker.

IMHO there are 2 ways, which can / will solve that in CMS 7:

* new Dashboard (where i plan to add the piwik widgets to)
* @pgampe 's suggested fix for selecting the last used or the first page in tree

with autoselection i have several concerns:

* what happens if you set a value, which is not allowed for the user
* the pagetree does not state the siteid which is currently shown

So this needs some detailed plan.

**Comment by kaystrobach** [comment]
@superscotty19 how about an integration in the CMS 7 Dashboard?

**Comment by superscotty19** [comment]
(Sorry for delayed response)
After attempting a massive upgrade from 4.5 LTS to 6.2 LTS to 7.6 LTS, my company concluded that 7.6 is not ready for prime time because it essentially nullifies most extensions with incompatibilities between them. So, we're sticking with 6.2. No matter, we've shifted our focus so that Statistics is not on the dashboard but still accessible via standard ways. Users are fine with this. Thanks again for your efforts to bring Piwik to TYPO3!
